### ISSUE TITLE
List your event on an events site

### ISSUE THREAD

**Issue by brandonkeao** [codefordenver/NDoCH#13]
Such as Eventbrite, Facebook, Meetup, and any others?

**Comment by wdoug** [comment]
My personal opinion is that we should have meetup be the primary location for info and point to it from Facebook and skip Eventbrite

**Comment by bminortx** [comment]
Code for Boulder will probably create another Meetup on our page that links to your Meetup. Most of our foot traffic comes from Meetup, so I think this is the best route for us.

**Comment by brandonkeao** [comment]
This will be really confusing from a marketing point of view and it will make tracking headcount that much harder. And if we message things out we need to do it in two places, and from a participant's view I won't be able to really see everyone who is coming...  

@wdoug @eemshi what do you think?

**Comment by eemshi** [comment]
@bminortx what if you message your meetup members with a link to our meetup event? is this possible?
