### ISSUE TITLE
Finalize event budget

### ISSUE THREAD

**Issue by brandonkeao** [codefordenver/NDoCH#8]

**Comment by brandonkeao** [comment]
Ballpark event budget is for food. Breakfast and Lunch for ~50 people. At least $500, shoot for $750 to be safe.

**Comment by wdoug** [comment]
In the past, for these larger events we've spent about $1000 for these large events for breakfast, and lunch with a few snacks and drinks.

**Comment by brandonkeao** [comment]
Okay, lets shoot for $1000 budge then and try to raise that amount.
